/**
 * MBAAS FrontEnd - MBAAS BackEnd - NSM Inspection
 * MBAAS (Mobile Backend As A Service) is the system in charge of ensuring exchanges between the SWITCH Information System 3DX and the mobile applications deployed on the terminals and web apps. In particular, it allows ID inspectors to carry out factory inspections via a mobile or web application in offline mode.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ApiError {
  code?: string;
  description?: string;
  severity?: ApiError.SeverityEnum;
  type?: ApiError.TypeEnum;
}
export namespace ApiError {
  export type SeverityEnum = 'INFO' | 'WARNING' | 'ERROR';
  export const SeverityEnum = {
    INFO: 'INFO' as SeverityEnum,
    WARNING: 'WARNING' as SeverityEnum,
    ERROR: 'ERROR' as SeverityEnum,
  };
  export type TypeEnum = 'TECHNICAL' | 'FUNCTIONAL';
  export const TypeEnum = {
    TECHNICAL: 'TECHNICAL' as TypeEnum,
    FUNCTIONAL: 'FUNCTIONAL' as TypeEnum,
  };
}

export interface ApiErrorDisplay {
  message: string;
  retryable?: boolean;
  code?: number;
}
