/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { MbaasUserInfo } from './mbaasUserInfo';
import { PageInfo } from './pageInfo';


export interface ApiResponseSetMbaasUserInfo { 
    content?: Array<MbaasUserInfo>;
    errors?: Array<ApiError>;
    page?: PageInfo;
}
