/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MbaasUserInfo } from './mbaasUserInfo';


export interface ConsultationEventLogDto { 
    comment?: string;
    /**
     * the creation date
     */
    creationDate: Date;
    status?: ConsultationEventLogDto.StatusEnum;
    user?: MbaasUserInfo;
}
export namespace ConsultationEventLogDto {
    export type StatusEnum = 'OPENED' | 'CANCELED' | 'CLOSED' | 'EXPIRED';
    export const StatusEnum = {
        OPENED: 'OPENED' as StatusEnum,
        CANCELED: 'CANCELED' as StatusEnum,
        CLOSED: 'CLOSED' as StatusEnum,
        EXPIRED: 'EXPIRED' as StatusEnum
    };
}
