/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FileMetadataDto { 
    checksum?: string;
    completionState?: FileMetadataDto.CompletionStateEnum;
    contentType?: string;
    description?: string;
    extension?: string;
    externalUuid?: string;
    fileNature?: FileMetadataDto.FileNatureEnum;
    fileProvider?: FileMetadataDto.FileProviderEnum;
    filename?: string;
    partNumber?: number;
    parts?: Array<FileMetadataDto>;
    physicalFilename?: string;
    size?: number;
    uuid?: string;
}
export namespace FileMetadataDto {
    export type CompletionStateEnum = 'ABORTED' | 'COMPLETED' | 'PARTIALLY_COMPLETED' | 'IN_PROGRESS' | 'FAILED';
    export const CompletionStateEnum = {
        ABORTED: 'ABORTED' as CompletionStateEnum,
        COMPLETED: 'COMPLETED' as CompletionStateEnum,
        PARTIALLYCOMPLETED: 'PARTIALLY_COMPLETED' as CompletionStateEnum,
        INPROGRESS: 'IN_PROGRESS' as CompletionStateEnum,
        FAILED: 'FAILED' as CompletionStateEnum
    };
    export type FileNatureEnum = 'ROOT' | 'PART';
    export const FileNatureEnum = {
        ROOT: 'ROOT' as FileNatureEnum,
        PART: 'PART' as FileNatureEnum
    };
    export type FileProviderEnum = 'NOT_PROVIDED' | 'MF_MBAAS' | 'MF_MBAAS_MOBILE' | 'MF' | 'APRISO' | 'MBAAS_MOBILE' | 'ESPN' | 'ESPN_MBAAS' | 'ESPN_MBAAS_FRONTEND' | 'ADMIN_MBAAS' | 'ADMIN_MBAAS_FRONTEND';
    export const FileProviderEnum = {
        NOTPROVIDED: 'NOT_PROVIDED' as FileProviderEnum,
        MFMBAAS: 'MF_MBAAS' as FileProviderEnum,
        MFMBAASMOBILE: 'MF_MBAAS_MOBILE' as FileProviderEnum,
        MF: 'MF' as FileProviderEnum,
        APRISO: 'APRISO' as FileProviderEnum,
        MBAASMOBILE: 'MBAAS_MOBILE' as FileProviderEnum,
        ESPN: 'ESPN' as FileProviderEnum,
        ESPNMBAAS: 'ESPN_MBAAS' as FileProviderEnum,
        ESPNMBAASFRONTEND: 'ESPN_MBAAS_FRONTEND' as FileProviderEnum,
        ADMINMBAAS: 'ADMIN_MBAAS' as FileProviderEnum,
        ADMINMBAASFRONTEND: 'ADMIN_MBAAS_FRONTEND' as FileProviderEnum
    };
}
