/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';

export interface MbaasUserInfo {
  /**
   * the email
   */
  email?: string;
  enabled?: boolean;
  firstName?: string;
  lastName?: string;
  nni?: string;
  roles?: Array<RoleDto>;
}
