/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileMetadataDto } from './fileMetadataDto';
import { LandPlotDto } from './landPlotDto';


/**
 * Class representing a consultation
 */
export interface MbaasConsultationDto { 
    comment?: string;
    /**
     * Unique identifier of the consultation. No two consultations can have the same externalUuid.
     */
    consultationId: string;
    documents?: Array<FileMetadataDto>;
    /**
     * Unique identifier of the consultation. No two consultations can have the same externalUuid.
     */
    externalUuid: string;
    landPlots?: Array<LandPlotDto>;
    planningCode?: string;
    status?: MbaasConsultationDto.StatusEnum;
    teleconsultationCode?: string;
    worksProjectsLabel?: string;
}
export namespace MbaasConsultationDto {
    export type StatusEnum = 'OPENED' | 'CANCELED' | 'CLOSED' | 'EXPIRED';
    export const StatusEnum = {
        OPENED: 'OPENED' as StatusEnum,
        CANCELED: 'CANCELED' as StatusEnum,
        CLOSED: 'CLOSED' as StatusEnum,
        EXPIRED: 'EXPIRED' as StatusEnum
    };
}
