/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MbaasFilter { 
    field?: string;
    operator?: MbaasFilter.OperatorEnum;
    value?: string;
    values?: Array<string>;
}
export namespace MbaasFilter {
    export type OperatorEnum = 'EQUALS' | 'LIKE' | 'IN' | 'STARTS_WITH' | 'CONTAINS';
    export const OperatorEnum = {
        EQUALS: 'EQUALS' as OperatorEnum,
        LIKE: 'LIKE' as OperatorEnum,
        IN: 'IN' as OperatorEnum,
        STARTSWITH: 'STARTS_WITH' as OperatorEnum,
        CONTAINS: 'CONTAINS' as OperatorEnum
    };
}
