/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PersonDto } from './personDto';
import { PostalAddressDto } from './postalAddressDto';

export interface NetworkProviderDto {
  networkProviderId?: string;
  address?: PostalAddressDto;
  agencyName?: string;
  companyName?: string;
  damagePhone?: string;
  email?: string;
  emergencyEmail?: string;
  emergencyFax?: string;
  emergencyPhone?: string;
  enabled?: boolean;
  fax?: string;
  name?: string;
  networkCode?: string;
  phone?: string;
  responsible?: PersonDto;
}
