/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PostalAddressDto { 
    city?: string;
    complementAddress?: string;
    postbox?: string;
    street?: string;
    streetNumber?: string;
    zipCode?: string;
}
