/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrivilegeDto } from './privilegeDto';

export interface RoleDto {
  assignmentDate?: Date;
  name?: UserRoleEnum;
  privileges?: Array<PrivilegeDto>;
}
export namespace RoleDto {
  export type NameEnum = 'NETWORK_MANAGER' | 'CONTRACTOR' | 'ADMIN';
  export const NameEnum = {
    NETWORKMANAGER: 'NETWORK_MANAGER' as NameEnum,
    CONTRACTOR: 'CONTRACTOR' as NameEnum,
    ADMIN: 'ADMIN' as NameEnum,
  };
}

// Added
export enum UserRoleEnum {
  NETWORK_MANAGER = 'NETWORK_MANAGER',
  FUNCTIONAL_ADMIN = 'FUNCTIONAL_ADMIN',
  CONTRACTOR = 'CONTRACTOR',
  SECURITY_MANAGER = 'SECURITY_MANAGER',
  CONTRACT_MANAGER = 'CONTRACT_MANAGER',
}

export const USER_ROLE_LABELS_MAP = {
  NETWORK_MANAGER: 'Gestionnaire de réseau',
  FUNCTIONAL_ADMIN: 'Administrateur fonctionnel',
  CONTRACTOR: 'Titulaire',
  SECURITY_MANAGER: 'Direction sécurité',
  CONTRACT_MANAGER: 'Gestionnaire du contrat',
};
