/**
 * KMU WAF API
 * KMU WAF API
 *
 * OpenAPI spec version: v1
 * Contact: youssef-externe.liouene@edf.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileMetadataDto } from './fileMetadataDto';
import { InvestigationDto } from './investigationDto';
import { NetworkProviderDto } from './networkProviderDto';


export interface WorkDeclarationDto { 
    cerfaDocumentsIneris?: Array<FileMetadataDto>;
    comment?: string;
    /**
     * the emission date
     */
    emissionDate: Date;
    externalUuid?: string;
    investigation?: InvestigationDto;
    investigationNeeded?: boolean;
    isNetworkPresent?: boolean;
    isNotSensitiveNetworkClassC?: boolean;
    isSensitiveNetworkClassC?: boolean;
    networkPlans?: Array<FileMetadataDto>;
    networkProvider?: NetworkProviderDto;
    otherDocumentsIneris?: Array<FileMetadataDto>;
    otherDocumentsReceipt?: Array<FileMetadataDto>;
    /**
     * the receipt date
     */
    receiptReceptionDate: Date;
    status?: WorkDeclarationDto.StatusEnum;
    workDeclarationId?: string;
}
export namespace WorkDeclarationDto {
    export type StatusEnum = 'OPENED' | 'CLOSED' | 'EXPIRED';
    export const StatusEnum = {
        OPENED: 'OPENED' as StatusEnum,
        CLOSED: 'CLOSED' as StatusEnum,
        EXPIRED: 'EXPIRED' as StatusEnum
    };
}
